#!/bin/sh
printf '%s\n' "Welcome to the Git server portion of plastic-cloud-to-ucb!"
printf '%s\n' "You've successfully authenticated, but I do not"
printf '%s\n' "provide interactive shell access."
exit 128
